# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

docker:
  - image: circleci/node:8

#
#
#
workflows:
  version: 2
  deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - coverage:
          requires:
            - test
      - publish:
          requires:
            - coverage

#
#
#
jobs:
  setup:
    working_directory: ~/m-repo

    steps:
      - checkout

      - run:
          name: "m: Install npm packages"
          command: "npm run setup:ci"

      - save_cache:
          paths:
            - node_modules
          key: m-{{ .Branch }}-{{ checksum "package-lock.json" }}

  test:
    docker:
      - image: circleci/node:8

    working_directory: ~/m-repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - m-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run:
          name: "m: Run linter"
          command: "npm run lint"

      - run:
          name: "m: Run tests"
          command: "npm test"

  coverage:
    docker:
      - image: circleci/node:8

    working_directory: ~/m-repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - m-{{ .Branch }}-{{ checksum "package-lock.json" }}

      # Uses COVERALLS environment variables
      - run:
          name: "m: Publish test coverage to COVERALLS"
          command: "npm run coverage"

  publish:
    docker:
      - image: circleci/node:8

    working_directory: ~/m-repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - m-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run:
          name: "m: Release to npm with semantic-release"
          command: "npx semantic-release"

