# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

workflows:
  version: 2
  build_test_coverage_publish:
    filters:
      branches:
        only:
          - master
    jobs:
      - setup
      - test:
          requires:
            - setup
      - coverage:
          requires:
            - test
      - publish:
          requires:
            - coverage

#
# Templates
#
job_defaults: &job_defaults
  working_directory: ~/m-repo
  docker:
    - image: circleci/node:8

#
#
#
jobs:
  setup:
    <<: *job_defaults

    steps:
      - checkout

      - run:
          name: "m: Install npm packages"
          command: "npm run setup:ci"

      - run:
          name: "m: Babel compile"
          command: "npm run build:ci"

      - save_cache:
          paths:
            - node_modules
            - dist
          key: m-{{ .Branch }}-{{ checksum "package.json" }}

  test:
    <<: *job_defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - m-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: "m: Run linter"
          command: "npm run lint"

      - run:
          name: "m: Run tests"
          command: "npm run test:ci"

  coverage:
    <<: *job_defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - m-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: "m: Publish test coverage to COVERALLS"
          command: "npm run coverage:ci"

  publish:
    <<: *job_defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - m-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: "m: Release to npm with semantic-release"
          command: "npx semantic-release"

